
public enum MenuEnum
{
    NONE,
    GENERAL_MENU,
    NEW_BOX,
    BOX,
    NEW_CONTEXT,
    MAP_BASE,
    MAP,
    NEW_GRAPH,
    HISTOGRAM_GRAPH,
    HISTOGRAM_BASE,
    SCATTERPLOT_GRAPH,
    SCATTERPLOT_BASE,
    PARENT,
    CHILD,
    ADD_CHILD,
    REMOVE_CHILD,
    DATA_POINT,
    ANIMATION,
    TRANSFORMATION,
    REMOVE_TRANSFORMATION,
    ANIMATED_TRANSFORMATION,
    DASHBOARD
}
